# Source - PostgreSQL
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=60000
debezium.source.database.hostname=uni-products-svc-postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=${POSTGRES_PASSWORD}
debezium.source.database.dbname=postgres
debezium.source.topic.prefix=uni-products-svc
debezium.source.table.include.list=public.products
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=debezium_slot
debezium.source.publication.name=debezium_pub
debezium.source.snapshot.mode=no_data
debezium.source.decimal.handling.mode=double

# Sink - AWS SQS
debezium.sink.type=sqs
debezium.sink.sqs.queue.url=${SQS_QUEUE_URL}
debezium.sink.sqs.region=${AWS_REGION}

# Format - clean JSON without schema
debezium.format.value=json
debezium.format.key=json
debezium.format.value.schemas.enable=false
debezium.format.key.schemas.enable=false
