/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"github.com/google/uuid"
	"strings"
	"time"
)


// ProductsAPIService ProductsAPI service
type ProductsAPIService service

type ApiProductsGetRequest struct {
	ctx context.Context
	ApiService *ProductsAPIService
	pageLimit *int32
	pageOffset *int32
	filterName *string
	filterPriceGte *float32
	filterPriceLte *float32
	filterCreatedAtGte *time.Time
	filterCreatedAtLte *time.Time
	sort *string
}

// Max number of items to return
func (r ApiProductsGetRequest) PageLimit(pageLimit int32) ApiProductsGetRequest {
	r.pageLimit = &pageLimit
	return r
}

// Number of items to skip
func (r ApiProductsGetRequest) PageOffset(pageOffset int32) ApiProductsGetRequest {
	r.pageOffset = &pageOffset
	return r
}

// Filter by product name (partial match)
func (r ApiProductsGetRequest) FilterName(filterName string) ApiProductsGetRequest {
	r.filterName = &filterName
	return r
}

// Filter products with price greater than or equal to this value
func (r ApiProductsGetRequest) FilterPriceGte(filterPriceGte float32) ApiProductsGetRequest {
	r.filterPriceGte = &filterPriceGte
	return r
}

// Filter products with price less than or equal to this value
func (r ApiProductsGetRequest) FilterPriceLte(filterPriceLte float32) ApiProductsGetRequest {
	r.filterPriceLte = &filterPriceLte
	return r
}

// Filter products created at or after this timestamp (RFC3339)
func (r ApiProductsGetRequest) FilterCreatedAtGte(filterCreatedAtGte time.Time) ApiProductsGetRequest {
	r.filterCreatedAtGte = &filterCreatedAtGte
	return r
}

// Filter products created at or before this timestamp (RFC3339)
func (r ApiProductsGetRequest) FilterCreatedAtLte(filterCreatedAtLte time.Time) ApiProductsGetRequest {
	r.filterCreatedAtLte = &filterCreatedAtLte
	return r
}

// Sort field and direction. Prefix &#x60;-&#x60; means descending order. Example: &#x60;sort&#x3D;price&#x60; (cheapest first), &#x60;sort&#x3D;-price&#x60; (most expensive first) 
func (r ApiProductsGetRequest) Sort(sort string) ApiProductsGetRequest {
	r.sort = &sort
	return r
}

func (r ApiProductsGetRequest) Execute() (*ProductsCollection, *http.Response, error) {
	return r.ApiService.ProductsGetExecute(r)
}

/*
ProductsGet Get products

Endpoint to retrieve a list of products with filtering, sorting and pagination.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiProductsGetRequest
*/
func (a *ProductsAPIService) ProductsGet(ctx context.Context) ApiProductsGetRequest {
	return ApiProductsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ProductsCollection
func (a *ProductsAPIService) ProductsGetExecute(r ApiProductsGetRequest) (*ProductsCollection, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ProductsCollection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProductsAPIService.ProductsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/products"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pageLimit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page[limit]", r.pageLimit, "form", "")
	} else {
		var defaultValue int32 = 20
		r.pageLimit = &defaultValue
	}
	if r.pageOffset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page[offset]", r.pageOffset, "form", "")
	} else {
		var defaultValue int32 = 0
		r.pageOffset = &defaultValue
	}
	if r.filterName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter[name]", r.filterName, "form", "")
	}
	if r.filterPriceGte != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter[price][gte]", r.filterPriceGte, "form", "")
	}
	if r.filterPriceLte != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter[price][lte]", r.filterPriceLte, "form", "")
	}
	if r.filterCreatedAtGte != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter[created_at][gte]", r.filterCreatedAtGte, "form", "")
	}
	if r.filterCreatedAtLte != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter[created_at][lte]", r.filterCreatedAtLte, "form", "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "form", "")
	} else {
		var defaultValue string = "-created_at"
		r.sort = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProductsPostRequest struct {
	ctx context.Context
	ApiService *ProductsAPIService
	createProduct *CreateProduct
}

func (r ApiProductsPostRequest) CreateProduct(createProduct CreateProduct) ApiProductsPostRequest {
	r.createProduct = &createProduct
	return r
}

func (r ApiProductsPostRequest) Execute() (*Product, *http.Response, error) {
	return r.ApiService.ProductsPostExecute(r)
}

/*
ProductsPost Create a new product

Endpoint to create a new product.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiProductsPostRequest
*/
func (a *ProductsAPIService) ProductsPost(ctx context.Context) ApiProductsPostRequest {
	return ApiProductsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Product
func (a *ProductsAPIService) ProductsPostExecute(r ApiProductsPostRequest) (*Product, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Product
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProductsAPIService.ProductsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/products"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createProduct == nil {
		return localVarReturnValue, nil, reportError("createProduct is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createProduct
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProductsProductIdDeleteRequest struct {
	ctx context.Context
	ApiService *ProductsAPIService
	productId uuid.UUID
}

func (r ApiProductsProductIdDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProductsProductIdDeleteExecute(r)
}

/*
ProductsProductIdDelete Delete a product

Endpoint to delete a product by its ID.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId product ID
 @return ApiProductsProductIdDeleteRequest
*/
func (a *ProductsAPIService) ProductsProductIdDelete(ctx context.Context, productId uuid.UUID) ApiProductsProductIdDeleteRequest {
	return ApiProductsProductIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
func (a *ProductsAPIService) ProductsProductIdDeleteExecute(r ApiProductsProductIdDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProductsAPIService.ProductsProductIdDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/products/{product_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"product_id"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v Errors
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
