/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProduct{}

// CreateProduct struct for CreateProduct
type CreateProduct struct {
	Data CreateProductData `json:"data"`
}

type _CreateProduct CreateProduct

// NewCreateProduct instantiates a new CreateProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProduct(data CreateProductData) *CreateProduct {
	this := CreateProduct{}
	this.Data = data
	return &this
}

// NewCreateProductWithDefaults instantiates a new CreateProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductWithDefaults() *CreateProduct {
	this := CreateProduct{}
	return &this
}

// GetData returns the Data field value
func (o *CreateProduct) GetData() CreateProductData {
	if o == nil {
		var ret CreateProductData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateProduct) GetDataOk() (*CreateProductData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateProduct) SetData(v CreateProductData) {
	o.Data = v
}

func (o CreateProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProduct := _CreateProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProduct)

	if err != nil {
		return err
	}

	*o = CreateProduct(varCreateProduct)

	return err
}

type NullableCreateProduct struct {
	value *CreateProduct
	isSet bool
}

func (v NullableCreateProduct) Get() *CreateProduct {
	return v.value
}

func (v *NullableCreateProduct) Set(val *CreateProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProduct(val *CreateProduct) *NullableCreateProduct {
	return &NullableCreateProduct{value: val, isSet: true}
}

func (v NullableCreateProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


