/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProductData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductData{}

// CreateProductData struct for CreateProductData
type CreateProductData struct {
	Type string `json:"type"`
	Attributes CreateProductDataAttributes `json:"attributes"`
}

type _CreateProductData CreateProductData

// NewCreateProductData instantiates a new CreateProductData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductData(type_ string, attributes CreateProductDataAttributes) *CreateProductData {
	this := CreateProductData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateProductDataWithDefaults instantiates a new CreateProductData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductDataWithDefaults() *CreateProductData {
	this := CreateProductData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateProductData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateProductData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateProductData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateProductData) GetAttributes() CreateProductDataAttributes {
	if o == nil {
		var ret CreateProductDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateProductData) GetAttributesOk() (*CreateProductDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateProductData) SetAttributes(v CreateProductDataAttributes) {
	o.Attributes = v
}

func (o CreateProductData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateProductData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProductData := _CreateProductData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProductData)

	if err != nil {
		return err
	}

	*o = CreateProductData(varCreateProductData)

	return err
}

type NullableCreateProductData struct {
	value *CreateProductData
	isSet bool
}

func (v NullableCreateProductData) Get() *CreateProductData {
	return v.value
}

func (v *NullableCreateProductData) Set(val *CreateProductData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductData(val *CreateProductData) *NullableCreateProductData {
	return &NullableCreateProductData{value: val, isSet: true}
}

func (v NullableCreateProductData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


