/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the ProductData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductData{}

// ProductData struct for ProductData
type ProductData struct {
	// product ID
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes ProductDataAttributes `json:"attributes"`
}

type _ProductData ProductData

// NewProductData instantiates a new ProductData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductData(id uuid.UUID, type_ string, attributes ProductDataAttributes) *ProductData {
	this := ProductData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewProductDataWithDefaults instantiates a new ProductData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDataWithDefaults() *ProductData {
	this := ProductData{}
	return &this
}

// GetId returns the Id field value
func (o *ProductData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProductData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProductData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ProductData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ProductData) GetAttributes() ProductDataAttributes {
	if o == nil {
		var ret ProductDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ProductData) GetAttributesOk() (*ProductDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ProductData) SetAttributes(v ProductDataAttributes) {
	o.Attributes = v
}

func (o ProductData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ProductData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductData := _ProductData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductData)

	if err != nil {
		return err
	}

	*o = ProductData(varProductData)

	return err
}

type NullableProductData struct {
	value *ProductData
	isSet bool
}

func (v NullableProductData) Get() *ProductData {
	return v.value
}

func (v *NullableProductData) Set(val *ProductData) {
	v.value = val
	v.isSet = true
}

func (v NullableProductData) IsSet() bool {
	return v.isSet
}

func (v *NullableProductData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductData(val *ProductData) *NullableProductData {
	return &NullableProductData{value: val, isSet: true}
}

func (v NullableProductData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


