/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProductDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductDataAttributes{}

// CreateProductDataAttributes struct for CreateProductDataAttributes
type CreateProductDataAttributes struct {
	// The name of the product
	Name string `json:"name"`
	// The price of the product
	Price float32 `json:"price"`
}

type _CreateProductDataAttributes CreateProductDataAttributes

// NewCreateProductDataAttributes instantiates a new CreateProductDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductDataAttributes(name string, price float32) *CreateProductDataAttributes {
	this := CreateProductDataAttributes{}
	this.Name = name
	this.Price = price
	return &this
}

// NewCreateProductDataAttributesWithDefaults instantiates a new CreateProductDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductDataAttributesWithDefaults() *CreateProductDataAttributes {
	this := CreateProductDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProductDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProductDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProductDataAttributes) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value
func (o *CreateProductDataAttributes) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CreateProductDataAttributes) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CreateProductDataAttributes) SetPrice(v float32) {
	o.Price = v
}

func (o CreateProductDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["price"] = o.Price
	return toSerialize, nil
}

func (o *CreateProductDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProductDataAttributes := _CreateProductDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProductDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateProductDataAttributes(varCreateProductDataAttributes)

	return err
}

type NullableCreateProductDataAttributes struct {
	value *CreateProductDataAttributes
	isSet bool
}

func (v NullableCreateProductDataAttributes) Get() *CreateProductDataAttributes {
	return v.value
}

func (v *NullableCreateProductDataAttributes) Set(val *CreateProductDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductDataAttributes(val *CreateProductDataAttributes) *NullableCreateProductDataAttributes {
	return &NullableCreateProductDataAttributes{value: val, isSet: true}
}

func (v NullableCreateProductDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


