/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsCollection{}

// ProductsCollection struct for ProductsCollection
type ProductsCollection struct {
	Data []ProductData `json:"data"`
	Links PaginationData `json:"links"`
}

type _ProductsCollection ProductsCollection

// NewProductsCollection instantiates a new ProductsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsCollection(data []ProductData, links PaginationData) *ProductsCollection {
	this := ProductsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewProductsCollectionWithDefaults instantiates a new ProductsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsCollectionWithDefaults() *ProductsCollection {
	this := ProductsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *ProductsCollection) GetData() []ProductData {
	if o == nil {
		var ret []ProductData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ProductsCollection) GetDataOk() ([]ProductData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ProductsCollection) SetData(v []ProductData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *ProductsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ProductsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ProductsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o ProductsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ProductsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductsCollection := _ProductsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductsCollection)

	if err != nil {
		return err
	}

	*o = ProductsCollection(varProductsCollection)

	return err
}

type NullableProductsCollection struct {
	value *ProductsCollection
	isSet bool
}

func (v NullableProductsCollection) Get() *ProductsCollection {
	return v.value
}

func (v *NullableProductsCollection) Set(val *ProductsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsCollection(val *ProductsCollection) *NullableProductsCollection {
	return &NullableProductsCollection{value: val, isSet: true}
}

func (v NullableProductsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


