/*
universe products API

API documentation for universe products service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ProductDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDataAttributes{}

// ProductDataAttributes struct for ProductDataAttributes
type ProductDataAttributes struct {
	// The name of the product
	Name string `json:"name"`
	// The price of the product
	Price float32 `json:"price"`
	// The date and time when the product was created
	CreatedAt time.Time `json:"created_at"`
}

type _ProductDataAttributes ProductDataAttributes

// NewProductDataAttributes instantiates a new ProductDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDataAttributes(name string, price float32, createdAt time.Time) *ProductDataAttributes {
	this := ProductDataAttributes{}
	this.Name = name
	this.Price = price
	this.CreatedAt = createdAt
	return &this
}

// NewProductDataAttributesWithDefaults instantiates a new ProductDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDataAttributesWithDefaults() *ProductDataAttributes {
	this := ProductDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *ProductDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductDataAttributes) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value
func (o *ProductDataAttributes) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *ProductDataAttributes) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *ProductDataAttributes) SetPrice(v float32) {
	o.Price = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProductDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProductDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProductDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ProductDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["price"] = o.Price
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ProductDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"price",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductDataAttributes := _ProductDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductDataAttributes)

	if err != nil {
		return err
	}

	*o = ProductDataAttributes(varProductDataAttributes)

	return err
}

type NullableProductDataAttributes struct {
	value *ProductDataAttributes
	isSet bool
}

func (v NullableProductDataAttributes) Get() *ProductDataAttributes {
	return v.value
}

func (v *NullableProductDataAttributes) Set(val *ProductDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDataAttributes(val *ProductDataAttributes) *NullableProductDataAttributes {
	return &NullableProductDataAttributes{value: val, isSet: true}
}

func (v NullableProductDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


