// Code generated by mockery v2.53.6. DO NOT EDIT.

package controller

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockMetrics is an autogenerated mock type for the metrics type
type mockMetrics struct {
	mock.Mock
}

// RecordCreated provides a mock function with given fields: ctx, err
func (_m *mockMetrics) RecordCreated(ctx context.Context, err error) {
	_m.Called(ctx, err)
}

// RecordDeleted provides a mock function with given fields: ctx, err
func (_m *mockMetrics) RecordDeleted(ctx context.Context, err error) {
	_m.Called(ctx, err)
}

// newMockMetrics creates a new instance of mockMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMetrics {
	mock := &mockMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
