// Code generated by mockery v2.53.6. DO NOT EDIT.

package controller

import (
	context "context"

	domain "github.com/paranoideed/uni-products-svc/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pagi "github.com/netbill/restkit/pagi"

	uuid "github.com/google/uuid"
)

// mockCore is an autogenerated mock type for the core type
type mockCore struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, req
func (_m *mockCore) CreateProduct(ctx context.Context, req domain.CreateProductRequest) (domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateProductRequest) (domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateProductRequest) domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, ID
func (_m *mockCore) DeleteProduct(ctx context.Context, ID uuid.UUID) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProducts provides a mock function with given fields: ctx, opts
func (_m *mockCore) GetProducts(ctx context.Context, opts ...domain.GetProductsOption) (pagi.Page[[]domain.Product], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 pagi.Page[[]domain.Product]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...domain.GetProductsOption) (pagi.Page[[]domain.Product], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...domain.GetProductsOption) pagi.Page[[]domain.Product]); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Get(0).(pagi.Page[[]domain.Product])
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...domain.GetProductsOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockCore creates a new instance of mockCore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCore {
	mock := &mockCore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
