// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pagi "github.com/netbill/restkit/pagi"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, req
func (_m *MockRepository) CreateProduct(ctx context.Context, req CreateProductRequest) (Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateProductRequest) (Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateProductRequest) Product); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, ID
func (_m *MockRepository) DeleteProduct(ctx context.Context, ID uuid.UUID) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProducts provides a mock function with given fields: ctx, opts
func (_m *MockRepository) GetProducts(ctx context.Context, opts GetProductsOptions) (pagi.Page[[]Product], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 pagi.Page[[]Product]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, GetProductsOptions) (pagi.Page[[]Product], error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetProductsOptions) pagi.Page[[]Product]); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(pagi.Page[[]Product])
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetProductsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
